local log = require("game.utils.log")

local function wait_until(fn)
	local co = coroutine.running()
	assert(co, "You must call this from within a coroutine")
	local wait = true
	timer.delay(0, true, function(self, handle, time_elapsed)
		if fn() then
			wait = false
			timer.cancel(handle)
		end
		local ok, err = coroutine.resume(co)
		if not ok then
			log("err", err)
			timer.cancel(handle)
			sys.exit(1)
		end
	end)
	while wait do
		coroutine.yield()
	end
end

local function wait(seconds)
	local co = coroutine.running()
	assert(co, "You must call this from within a coroutine")
	timer.delay(seconds, false, function(self, handle, time_elapsed)
		local ok, err = coroutine.resume(co)
		if not ok then
			log("err", err)
			sys.exit(1)
		end
	end)
	coroutine.yield()
end

local function connect()
	local userid = ("user" .. math.random(999999))
	log("connect userid: '%s'", userid)
	fusion.on_event(function(self, event_id, event)
		if event_id == fusion.EVENT_OBJECT_OWNER_CHANGED then
			--msg.post(event.id, fusion.EVENT_OBJECT_OWNER_CHANGED, event)
		elseif event_id == fusion.EVENT_OBJECT_READY then
			--msg.post(event.id, fusion.EVENT_OBJECT_READY, event)
		end
	end)

	fusion.connect(userid)
	wait_until(function()
		--log("connect waiting until connected")
		return fusion.is_connected()
	end)
end

local function join_room(name)
	name = name or "foo"
	log("join_room name: '%s'", name)
	local room_options = {
		is_visible = true,
		is_open = true,
		max_players = 10,
		lobby_name = name,
		custom_properties = {
			foo = "bar",
			baz = 1,
			boo = true
		}
	}
	local matchmaking_options = {
		max_players = 10,
		lobby_name = name,
	}
	fusion.join_or_create_room_random(room_options, matchmaking_options)
	wait_until(function()
		return fusion.is_in_room()
	end)
end

local function start_game()
	log("start game")
	fusion.start()
	wait_until(function()
		return fusion.is_started()
	end)
end

local function load_level()
	local url = "#level"
	local status = collectionfactory.get_status(url)
	if status == collectionfactory.STATUS_UNLOADED then
		collectionfactory.load(url, function() end)
	end
	wait_until(function()
		return collectionfactory.get_status(url) == collectionfactory.STATUS_LOADED
	end)
	local pos = vmath.vector3(0)
	collectionfactory.create(url, pos)
end

local function spawn_player()
	log("spawn player")
	local pos = vmath.vector3(0,3,0)
	local rot = nil
	local scene = 1
	local owner_mode = fusion.OWNERMODE_PLAYERATTACHED
	local options = {
		properties = {
			player = { "net_coins", "net_is_grounded" }
		},
		replication_mode = fusion.REPLICATION_MODE_AUTO,
	}
	local id = fusion.spawn("game#playerfactory", pos, rot, scene, owner_mode, options)
	log("spawned player with id %s", id)
	msg.post("camera", "follow", { url = id })
end


local function start_connect_flow()
	coroutine.wrap(function()
		fusion.init_from_settings()
		fusion.enable_debug(true)
		connect()
		join_room()
		start_game()
		load_level()
		spawn_player()
	end)()
end

function init(self)
	sys.set_error_handler(function(source, message, traceback)
		log("ERROR: (%s) %s %s", source, message, traceback)
	end)
	local index = sys.get_config_int("project.instance_index", 1)
	log(index)
	math.randomseed(os.time() + index)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start_connect_flow") then
		start_connect_flow()
	end
end
