-- Collectible coin that respawns after a cooldown. Uses client-side prediction
-- for immediate visual feedback.

local game_context = require("game.context")
local messages = require("game.messages")
local groups = require("game.groups")

go.property("net_active", true)

local COOLDOWN_TIMER_DELAY = 6


local function set_active(self, active)
	self.net_active = active
	if active then
		particlefx.play("#coinsparkle")
		msg.post("#model", "enable")
		msg.post("#collisionobject", "enable")
	else
		particlefx.stop("#coinsparkle")
		msg.post("#model", "disable")
		msg.post("#collisionobject", "disable")
	end
end

function init(self)
	local props = {
		[msg.url().fragment] = { "net_active" }
	}
	fusion.create_map_object(1, fusion.OWNERMODE_PLAYERATTACHED, props)
	
	fusion.subscribe_rpc(messages.RPC_COLLECTED)

	self.time = 0
	self.original_position = go.get_position()
	set_active(self, true)
end

function final(self)
	fusion.unsubscribe_rpc(messages.RPC_COLLECTED)
end

function update(self, dt)
	local rot = go.get_rotation()
	rot = rot * vmath.quat_rotation_y(math.rad(40) * dt)
	go.set_rotation(rot)

	local pos = vmath.vector3(self.original_position)
	pos.y = pos.y + math.abs(math.cos(math.rad(self.time * 40))) * 0.2
	go.set_position(pos)

	self.time = self.time + dt
end

function on_message(self, message_id, message, sender)
	if message_id == messages.COLLISION_RESPONSE then
		if message.other_group == groups.PLAYER then
			print("collide with coin! local player id: ", game_context.local_player, "other id:", message.other_id)
			if game_context.local_player == message.other_id then
				-- send rpc to the coin on the owning client
				local coin_id = go.get_id()
				local owner_id = fusion.get_owner_id(coin_id)
				local target_object_id = coin_id
				local data = { collector_id = owner_id, coin_id = coin_id }
				local ok = fusion.send_rpc(owner_id, target_object_id, messages.RPC_REQUEST_COLLECTED, data)
				--local ok = fusion.send_rpc(fusion.OBJECT_OWNER_PLAYER_ID, target_object_id, messages.RPC_REQUEST_COLLECTED, data)
				if not ok then
					print("Error sending rpc")
					return
				end

				-- Even clients without authority will temporarily modify (predict) this networked
				-- property to have immediate visual feedback. Process method makes sure the coin
				-- disappears and particle is stopped.
				--set_active(self, false)
				msg.post("#collisionobject", "disable")
			end
		end
	elseif message_id == messages.RPC_REQUEST_COLLECTED then
		print("coin rpc_request_collect")
		if not self.net_active then
			return
		end

		set_active(self, false)
		timer.delay(COOLDOWN_TIMER_DELAY, false, function()
			set_active(self, true)
		end)
		-- send to the player who collected the coin
		fusion.send_rpc(message.data.collector_id, go.get_id(), messages.RPC_COLLECTED)
	elseif message_id == messages.RPC_COLLECTED then
		msg.post(game_context.local_player, messages.COIN_COLLECTED)
		sound.play("/sounds#coin")
	elseif message_id == fusion.EVENT_OBJECT_READY then
		print("coin is ready", go.get_id(), "my owner is", fusion.get_owner_id())
	elseif message_id == fusion.EVENT_OBJECT_OWNER_CHANGED then
		print("coin owner changed")
		pprint(message)
	end
end