local context = require("game.context")

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#", "toggle_log")
end

function update(self, dt)
	if not self.start then
		return
	end
	local instance_index = sys.get_config_int("project.instance_index", 1)
	local is_started = fusion.is_started()
	local is_running = fusion.is_running()
	local is_connected = fusion.is_connected()
	local is_in_room = fusion.is_in_room()
	local is_master = fusion.is_master_client()
	local player_count = fusion.player_count()
	local player_id = fusion.get_local_player_id()
	local s = ""
	s = s .. "Instance no: " .. instance_index .. "\n"
	s = s .. "Connected: " .. (is_connected and "YES" or "NO") .. "\n"
	s = s .. "Master: " .. (is_master and "YES" or "NO") .. "\n"
	s = s .. "Running: " .. (is_running and "YES" or "NO") .. "\n"
	s = s .. "Started: " .. (is_started and "YES" or "NO") .. "\n"
	s = s .. "In room: " .. (is_in_room and "YES" or "NO") .. "\n"
	s = s .. "Player Count: " .. player_count .. "\n"
	s = s .. "Map id: " .. (context.map and context.map or "?") .. "\n"
	s = s .. "Player id: " .. player_id .. "\n"
		gui.set_text(gui.get_node("info"), s)
end


function on_message(self, message_id, message, sender)
	if message_id == hash("start") then
		self.start = true
	elseif message_id == hash("toggle_log") then
		local node = gui.get_node("info")
		gui.set_enabled(node, not gui.is_enabled(node))
	end
end

function on_input(self, action_id, action)
	if action_id == hash("toggle_log") then
		if action.pressed then
			msg.post("#", "toggle_log")
		end
	end
end