local game_context = require("game.context")
local messages = require("game.messages")
local groups = require("game.groups")

function on_message(self, message_id, message, sender)
	if message_id == messages.COLLISION_RESPONSE then
		if message.other_group == groups.PLAYER then
			if fusion.is_master_client() then
				msg.post(game_context.game, messages.FLAG_REACHED, { player_id = message.other_id })
			end
		end
	end
end

