local ui = require("game.utils.ui")

function init(self)
	msg.post(".", "acquire_input_focus")
	
	local username = "user" .. tostring(math.floor(math.random() * 100000))
	gui.set_text(gui.get_node("username"), username)
end

function on_input(self, action_id, action)
	local username = ui.input(self, "username", action_id, action)
	local roomname = ui.input(self, "roomname", action_id, action)
	if ui.button(self, "start_game", action) then
		ui.hide("login_panel")
		msg.post(".", "start_connect_flow", { username = username, roomname = roomname })
	end
	if action.released and action_id == hash("toggle_debug") then
		msg.post("@system:", "toggle_physics_debug")
	end
end